// lib/context-menu.js — Context menu build & click handling
import { PromptStorage, LocalStorage } from './storage.js';
import { translations } from '../locales.js';
import {
    extractTitleHeuristic,
    detectLanguageHeuristic,
    matchCategory,
    buildDeferredMetadata,
    shouldEnrichPromptMetadata
} from './text-analysis.js';
import { extractVariables } from './variables.js';
import { getActiveProvider } from './ai/provider.js';
import { smartConvertWithAI, isSmartConvertInputValid, SMART_CONVERT_MIN_LENGTH } from './ai/smart-convert.js';

// --- Context Menu Constants ---
export const AI_PLATFORMS = [
    { id: 'chatgpt', name: 'ChatGPT', url: 'https://chatgpt.com/' },
    { id: 'claude', name: 'Claude', url: 'https://claude.ai/new' },
    { id: 'gemini', name: 'Gemini', url: 'https://gemini.google.com/app' },
    { id: 'deepseek', name: 'DeepSeek', url: 'https://chat.deepseek.com/' },
    { id: 'kimi', name: 'Kimi', url: 'https://kimi.com/' },
    { id: 'doubao', name: '豆包', url: 'https://www.doubao.com/' },
    { id: 'qwen', name: '通义千问', url: 'https://chat.qwen.ai/' },
];

// Content script match patterns for detection
export const AI_CHAT_PATTERNS = [
    'chat.openai.com', 'chatgpt.com', 'claude.ai', 'gemini.google.com',
    'notebooklm.google.com', 'aistudio.google.com', 'grok.com',
    'chat.deepseek.com', 'kimi.com', 'kimi.moonshot.cn', 'chatglm.cn',
    'doubao.com', 'yiyan.baidu.com', 'tongyi.aliyun.com', 'chat.qwen.ai',
    'hailuoai.com', 'hunyuan.tencent.com'
];

const PROMPT_DELIVERY_INITIAL_DELAY_MS = 600;
const PROMPT_DELIVERY_RETRY_MS = 250;
const PROMPT_DELIVERY_VERIFY_DELAY_MS = 700;
const PROMPT_DELIVERY_MAX_ATTEMPTS = 12;

function buildSavedPromptMetadata(content, metadata = {}) {
    return buildDeferredMetadata(content, {
        title: metadata.title,
        category: metadata.category,
        tags: metadata.tags,
        titleAutoGenerated: metadata.titleAutoGenerated,
        categoryAutoGenerated: metadata.categoryAutoGenerated,
    });
}

export async function getDefaultPlatform() {
    const defaultPlatform = await LocalStorage.get('defaultPlatform');
    return defaultPlatform || 'chatgpt';
}

export function isAIChatUrl(url) {
    if (!url) return false;
    return AI_CHAT_PATTERNS.some(pattern => url.includes(pattern));
}

const GENERIC_PAGE_ALLOWED_CONTEXT_VARS = new Set(['@page_text', '@selection', '@page_url', '@page_title', '@date']);

function isGenericPageContextPrompt(prompt) {
    if (!prompt?.content) return false;

    const variableNames = extractVariables(prompt.content).map(v => v.name);
    const hasAllowedContextVar = variableNames.some(name => GENERIC_PAGE_ALLOWED_CONTEXT_VARS.has(name));
    if (!hasAllowedContextVar) return false;

    return (
        prompt.builtIn === true ||
        prompt.category === 'Context Grabber ★' ||
        /^📸\s/.test(String(prompt.title || ''))
    );
}

function getContextMenuPrompts(prompts) {
    return prompts.filter(isGenericPageContextPrompt);
}

export async function openPromptInDefaultAI(content) {
    if (!content) return;

    const platformId = await getDefaultPlatform();
    const platform = AI_PLATFORMS.find(p => p.id === platformId) || AI_PLATFORMS[0];

    const newTab = await chrome.tabs.create({ url: platform.url });
    await LocalStorage.set('pendingPrompt', {
        content,
        targetTabId: newTab.id,
        createdAt: Date.now()
    });

    const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));
    const normalizePromptText = (value) => String(value || '').replace(/\r\n/g, '\n').trim();
    const getPendingContentForTab = async (tabId) => {
        const pendingPrompt = await LocalStorage.get('pendingPrompt');
        return typeof pendingPrompt === 'string'
            ? pendingPrompt
            : (pendingPrompt?.targetTabId === tabId ? pendingPrompt.content : null);
    };

    const verifyPromptInTab = async (tabId, expectedContent) => {
        await sleep(PROMPT_DELIVERY_VERIFY_DELAY_MS);
        try {
            const response = await chrome.tabs.sendMessage(tabId, { type: 'GET_ACTIVE_INPUT_TEXT' });
            return normalizePromptText(response?.text) === normalizePromptText(expectedContent);
        } catch (e) {
            return false;
        }
    };

    const deliverPromptToTab = async (tabId) => {
        await sleep(PROMPT_DELIVERY_INITIAL_DELAY_MS);

        for (let attempt = 0; attempt < PROMPT_DELIVERY_MAX_ATTEMPTS; attempt += 1) {
            const pendingContent = await getPendingContentForTab(tabId);

            if (!pendingContent) return false;

            try {
                const response = await chrome.tabs.sendMessage(tabId, {
                    type: 'INSERT_PROMPT',
                    content: pendingContent,
                    suppressNotifications: true
                });
                if (response?.success) {
                    const verified = await verifyPromptInTab(tabId, pendingContent);
                    if (verified) {
                        await LocalStorage.remove('pendingPrompt');
                        return true;
                    }
                }
            } catch (e) { /* Retry until editor is ready */ }

            await sleep(PROMPT_DELIVERY_RETRY_MS);
        }

        return false;
    };

    let deliveryStarted = false;
    const startDelivery = async (tabId) => {
        if (deliveryStarted) return;
        deliveryStarted = true;
        await deliverPromptToTab(tabId);
    };

    const listener = async (tabId, changeInfo) => {
        if (tabId === newTab.id && changeInfo.status === 'complete') {
            chrome.tabs.onUpdated.removeListener(listener);
            await startDelivery(tabId);
        }
    };
    chrome.tabs.onUpdated.addListener(listener);

    try {
        const currentTab = await chrome.tabs.get(newTab.id);
        if (currentTab?.status === 'complete') {
            chrome.tabs.onUpdated.removeListener(listener);
            await startDelivery(newTab.id);
        }
    } catch (e) { /* Tab may close before initial delivery */ }
}

async function notifyContextPromptUnavailable(tabId) {
    if (!tabId) return;

    const message = chrome.i18n.getUILanguage().startsWith('zh')
        ? '无法获取当前页面上下文，请刷新页面后重试'
        : 'Unable to read the current page context. Refresh the page and try again.';

    try {
        await chrome.scripting.executeScript({
            target: { tabId },
            func: (msg) => {
                const existing = document.getElementById('apm-context-prompt-error');
                if (existing) existing.remove();

                const toast = document.createElement('div');
                toast.id = 'apm-context-prompt-error';
                toast.textContent = `❌ ${msg}`;
                toast.style.cssText = 'position:fixed;top:20px;right:20px;z-index:2147483647;padding:12px 20px;background:#ef4444;color:#fff;border-radius:8px;font-size:14px;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 4px 12px rgba(0,0,0,0.3);';
                document.body.appendChild(toast);
                setTimeout(() => {
                    toast.style.opacity = '0';
                    toast.style.transition = 'opacity 0.3s';
                    setTimeout(() => toast.remove(), 300);
                }, 2600);
            },
            args: [message]
        });
    } catch (e) {
        console.warn('[ContextMenu] Failed to show context prompt error toast:', e);
    }
}

// Serialized context menu builder: queues concurrent calls instead of dropping them
let _buildMenusChain = Promise.resolve();
let _buildMenusPending = false;

// Await-able wrapper for chrome.contextMenus.create
function createMenu(props) {
    return new Promise((resolve) => chrome.contextMenus.create(props, resolve));
}

async function markPendingPromptReveal(promptId) {
    if (!promptId) return;
    try {
        await chrome.storage.local.set({
            pendingPromptReveal: {
                id: String(promptId),
                timestamp: Date.now()
            }
        });
    } catch (e) {
        console.warn('[PromptReveal] Failed to persist pending prompt id:', e);
    }
}

/**
 * Build context menus. Queues concurrent calls to avoid race conditions.
 * @param {Function} getPromptsFn - Injected to access prompt list
 */
export async function buildContextMenus(getPromptsFn, options = {}) {
    if (_buildMenusPending) return;
    _buildMenusPending = true;
    _buildMenusChain = _buildMenusChain
        .then(() => _doBuildContextMenus(getPromptsFn, options))
        .catch(e => console.error('[buildContextMenus] error:', e))
        .finally(() => { _buildMenusPending = false; });
    return _buildMenusChain;
}

async function _doBuildContextMenus(getPromptsFn, options = {}) {
    try {
        const { language } = await chrome.storage.local.get('language');
        let locale = language;
        if (!locale) {
            locale = chrome.i18n.getUILanguage().startsWith('zh') ? 'zh_CN' : 'en';
        }
        const dict = translations[locale] || translations['en'];
        const t = (key, fallback) => dict[key] || fallback;

        await chrome.contextMenus.removeAll();

        // Top-level action 1: save selected text as-is
        await createMenu({
            id: 'prompt-ark-add',
            title: t('contextMenuAddPrompt', 'Add to Prompt Ark'),
            contexts: ['selection']
        });

        // Top-level action 2: AI rewrites content into a reusable prompt
        await createMenu({
            id: 'prompt-ark-convert',
            title: t('contextMenuConvertPrompt', 'Smart Convert to Prompt'),
            contexts: ['selection']
        });

        const prompts = getContextMenuPrompts(await getPromptsFn());

        if (prompts.length > 0) {
            const menuItems = prompts;

            if (menuItems.length > 0) {
                const listLabel = t('contextMenuPromptsList', 'Prompts List');
                await createMenu({
                    id: 'prompt-ark-parent',
                    title: listLabel,
                    contexts: ['selection', 'page']
                });

                for (const p of menuItems) {
                    await createMenu({
                        id: `prompt-ark-${p.id}`,
                        parentId: 'prompt-ark-parent',
                        title: p.title,
                        contexts: ['selection', 'page']
                    });
                }
            }
        }

        // Share Article sub-menu
        const shareArticleLabel = t('contextMenuShareArticle', 'Share Article to...');
        await createMenu({
            id: 'prompt-ark-share-article',
            title: shareArticleLabel,
            contexts: ['selection', 'page']
        });
        const articlePlatforms = [
            { id: 'zhihu', label: t('contextMenuZhihu', '知乎') },
            { id: 'reddit', label: t('contextMenuReddit', 'Reddit') },
            { id: 'wechat', label: t('contextMenuWechat', 'WeChat') },
            { id: 'linkedin', label: t('contextMenuLinkedIn', 'LinkedIn') },
            { id: 'xiaohongshu', label: t('contextMenuXiaohongshu', '小红书') },
            { id: 'twitter', label: t('contextMenuTwitter', 'Twitter/X') },
        ];
        for (const p of articlePlatforms) {
            await createMenu({
                id: `share-article-${p.id}`,
                parentId: 'prompt-ark-share-article',
                title: p.label,
                contexts: ['selection', 'page']
            });
        }
    } finally {
        // (no flag to reset — managed by promise chain)
    }
}

/**
 * Handle context menu click.
 * @param {Object} info - chrome.contextMenus click info
 * @param {Object} tab - Active tab
 * @param {Function} getPromptsFn - Prompt list accessor
 * @param {Function} asyncEnrichPromptFn - Async enrichment injected
 * @param {Function} buildContextMenusFn - Rebuild menus on change
 */
export async function handleContextMenuClick(info, tab, getPromptsFn, asyncEnrichPromptFn, buildContextMenusFn) {
    const menuId = info.menuItemId;

    // --- Share Article to platform ---
    if (typeof menuId === 'string' && menuId.startsWith('share-article-')) {
        const platform = menuId.replace('share-article-', '');
        if (tab?.id) {
            try {
                await chrome.tabs.sendMessage(tab.id, {
                    type: 'ARTICLE_SHARE_PICK_PLATFORM',
                    platform,
                });
            } catch (e) {
                console.warn('[ContextMenu] Failed to send article share:', e);
            }
        }
        return;
    }

    // --- Smart Convert to Prompt ---
    if (menuId === 'prompt-ark-convert') {
        const selectedText = (info.selectionText || '').trim();
        if (!selectedText) return;
        if (!isSmartConvertInputValid(selectedText)) {
            if (tab?.id) {
                try {
                    await chrome.tabs.sendMessage(tab.id, { type: 'SMART_CONVERT_STATUS', status: 'too_short' });
                } catch (e) {
                    try {
                        await chrome.scripting.executeScript({
                            target: { tabId: tab.id },
                            func: (msg) => {
                                const n = document.createElement('div');
                                n.textContent = '❌ ' + msg;
                                n.style.cssText = 'position:fixed;top:20px;right:20px;z-index:999999;padding:12px 20px;background:#ef4444;color:white;border-radius:8px;font-size:14px;font-family:system-ui;box-shadow:0 4px 12px rgba(0,0,0,0.3);';
                                document.body.appendChild(n);
                                setTimeout(() => { n.style.opacity = '0'; setTimeout(() => n.remove(), 300); }, 3500);
                            },
                            args: [chrome.i18n.getMessage('smartConvertTooShort') || `Smart Convert requires at least ${SMART_CONVERT_MIN_LENGTH} characters.`]
                        });
                    } catch (e2) { /* OK */ }
                }
            }
            return;
        }

        const provider = await getActiveProvider();
        if (!provider) {
            if (tab?.id) {
                try {
                    await chrome.tabs.sendMessage(tab.id, { type: 'SMART_CONVERT_STATUS', status: 'no_provider' });
                } catch (e) {
                    try {
                        await chrome.scripting.executeScript({
                            target: { tabId: tab.id },
                            func: (msg) => {
                                const n = document.createElement('div');
                                n.textContent = '❌ ' + msg;
                                n.style.cssText = 'position:fixed;top:20px;right:20px;z-index:999999;padding:12px 20px;background:#ef4444;color:white;border-radius:8px;font-size:14px;font-family:system-ui;box-shadow:0 4px 12px rgba(0,0,0,0.3);';
                                document.body.appendChild(n);
                                setTimeout(() => { n.style.opacity = '0'; setTimeout(() => n.remove(), 300); }, 3500);
                            },
                            args: [chrome.i18n.getMessage('smartConvertNoProvider') || 'Smart Convert requires an AI provider. Configure one in Prompt Ark settings.']
                        });
                    } catch (e2) { /* OK */ }
                }
            }
            return;
        }

        // Show "processing" toast
        if (tab?.id) {
            try {
                await chrome.tabs.sendMessage(tab.id, { type: 'SMART_CONVERT_STATUS', status: 'start' });
            } catch (e) {
                try {
                    await chrome.scripting.executeScript({
                        target: { tabId: tab.id },
                        func: (msg) => {
                            const n = document.createElement('div');
                            n.id = 'apm-smart-convert-toast';
                            n.textContent = '⏳ ' + msg;
                            n.style.cssText = 'position:fixed;top:20px;right:20px;z-index:999999;padding:12px 20px;background:rgba(15,23,42,0.92);color:white;border-radius:8px;font-size:14px;font-family:system-ui;box-shadow:0 4px 12px rgba(0,0,0,0.3);border:1px solid rgba(255,255,255,0.15);';
                            document.body.appendChild(n);
                        },
                        args: [chrome.i18n.getMessage('contextMenuConvertStart') || 'Converting to prompt...']
                    });
                } catch (e2) { /* OK */ }
            }
        }

        let savedTitle = '';
        try {
            const result = await smartConvertWithAI(selectedText);
            if (!result?.prompt) throw new Error('Empty result from AI');
            const metadata = buildSavedPromptMetadata(result.prompt, {
                title: result.title,
                category: result.category,
                tags: result.tags,
                titleAutoGenerated: !String(result.title || '').trim(),
                categoryAutoGenerated: !String(result.category || '').trim(),
            });

            const newId = crypto.randomUUID();
            const newPrompt = {
                id: newId,
                title: metadata.title,
                content: result.prompt,
                category: metadata.category,
                tags: metadata.tags,
                shortcut: '',
                variables: extractVariables(result.prompt),
                versions: [],
                usageCount: 0,
                lastUsedAt: null,
                favorite: false,
                titleAutoGenerated: metadata.titleAutoGenerated,
                categoryAutoGenerated: metadata.categoryAutoGenerated,
                sourceContext: {
                    text: selectedText.substring(0, 5000),
                    pageTitle: tab?.title || '',
                    pageUrl: tab?.url || '',
                    capturedAt: Date.now(),
                    convertMethod: 'smart_convert',
                },
                createdAt: Date.now()
            };
            savedTitle = newPrompt.title;
            await PromptStorage.save(newPrompt);
            await buildContextMenusFn();
            await markPendingPromptReveal(newId);
            try { chrome.runtime.sendMessage({ type: 'PROMPTS_UPDATED', action: 'create', promptId: newId, prompt: newPrompt }); } catch { /* popup may be closed */ }
            if (shouldEnrichPromptMetadata(newPrompt)) {
                await asyncEnrichPromptFn(newId, newPrompt.content);
            }

            // Show success toast
            if (tab?.id) {
                try {
                    await chrome.tabs.sendMessage(tab.id, { type: 'SMART_CONVERT_STATUS', status: 'success', title: savedTitle });
                } catch (e) {
                    try {
                        await chrome.scripting.executeScript({
                            target: { tabId: tab.id },
                            func: (title, msg) => {
                                document.getElementById('apm-smart-convert-toast')?.remove();
                                const n = document.createElement('div');
                                n.textContent = `✨ ${msg}: "${title}"`;
                                n.style.cssText = 'position:fixed;top:20px;right:20px;z-index:999999;padding:12px 20px;background:#10b981;color:white;border-radius:8px;font-size:14px;font-family:system-ui;box-shadow:0 4px 12px rgba(0,0,0,0.3);';
                                document.body.appendChild(n);
                                setTimeout(() => { n.style.opacity = '0'; n.style.transition = 'opacity 0.3s'; setTimeout(() => n.remove(), 300); }, 3000);
                            },
                            args: [savedTitle, chrome.i18n.getMessage('contextMenuConvertSuccess') || 'Smart prompt saved!']
                        });
                    } catch (e2) { /* OK */ }
                }
            }
        } catch (e) {
            console.error('[SmartConvert] AI call failed, falling back to raw save:', e);
            const heuristicTitle = extractTitleHeuristic(selectedText);
            const lang = detectLanguageHeuristic(selectedText);
            const metadata = buildSavedPromptMetadata(selectedText, {
                title: heuristicTitle,
                category: matchCategory(selectedText, lang),
                tags: [],
                titleAutoGenerated: true,
                categoryAutoGenerated: true,
            });
            const fallbackId = crypto.randomUUID();
            const fallbackPrompt = {
                id: fallbackId,
                title: metadata.title,
                content: selectedText,
                category: metadata.category,
                tags: metadata.tags,
                shortcut: '',
                variables: extractVariables(selectedText),
                versions: [],
                usageCount: 0,
                lastUsedAt: null,
                favorite: false,
                titleAutoGenerated: metadata.titleAutoGenerated,
                categoryAutoGenerated: metadata.categoryAutoGenerated,
                sourceContext: {
                    text: selectedText.substring(0, 5000),
                    pageTitle: tab?.title || '',
                    pageUrl: tab?.url || '',
                    capturedAt: Date.now(),
                    convertMethod: 'smart_convert',
                },
                createdAt: Date.now()
            };
            await PromptStorage.save(fallbackPrompt);
            await buildContextMenusFn();
            await markPendingPromptReveal(fallbackId);
            try { chrome.runtime.sendMessage({ type: 'PROMPTS_UPDATED', action: 'create', promptId: fallbackId, prompt: fallbackPrompt }); } catch { /* OK */ }
            if (shouldEnrichPromptMetadata(fallbackPrompt)) {
                await asyncEnrichPromptFn(fallbackId, fallbackPrompt.content);
            }

            // Show error toast
            if (tab?.id) {
                try {
                    await chrome.tabs.sendMessage(tab.id, { type: 'SMART_CONVERT_STATUS', status: 'error' });
                } catch (err) {
                    try {
                        await chrome.scripting.executeScript({
                            target: { tabId: tab.id },
                            func: (msg) => {
                                document.getElementById('apm-smart-convert-toast')?.remove();
                                const n = document.createElement('div');
                                n.textContent = '❌ ' + msg;
                                n.style.cssText = 'position:fixed;top:20px;right:20px;z-index:999999;padding:12px 20px;background:#f59e0b;color:white;border-radius:8px;font-size:14px;font-family:system-ui;box-shadow:0 4px 12px rgba(0,0,0,0.3);';
                                document.body.appendChild(n);
                                setTimeout(() => { n.style.opacity = '0'; n.style.transition = 'opacity 0.3s'; setTimeout(() => n.remove(), 300); }, 3500);
                            },
                            args: [chrome.i18n.getMessage('contextMenuConvertError') || 'Smart Convert failed, saved as raw text']
                        });
                    } catch (e2) { /* OK */ }
                }
            }
        }
        return;
    }

    // --- Add to Prompt Ark ---
    if (menuId === 'prompt-ark-add') {
        const selectedText = (info.selectionText || '').trim();
        if (!selectedText) return;

        const heuristicTitle = extractTitleHeuristic(selectedText);
        const lang = detectLanguageHeuristic(selectedText);
        const heuristicCategory = matchCategory(selectedText, lang);
        const metadata = buildSavedPromptMetadata(selectedText, {
            title: heuristicTitle,
            category: heuristicCategory,
            tags: [],
            titleAutoGenerated: true,
            categoryAutoGenerated: true,
        });

        const newId = crypto.randomUUID();
        const newPrompt = {
            id: newId,
            title: metadata.title,
            content: selectedText,
            category: metadata.category,
            tags: metadata.tags,
            shortcut: '',
            variables: extractVariables(selectedText),
            versions: [],
            usageCount: 0,
            lastUsedAt: null,
            favorite: false,
            titleAutoGenerated: metadata.titleAutoGenerated,
            categoryAutoGenerated: metadata.categoryAutoGenerated,
            sourceContext: {
                text: selectedText.substring(0, 5000),
                pageTitle: tab?.title || '',
                pageUrl: tab?.url || '',
                capturedAt: Date.now(),
                convertMethod: 'quick_add',
            },
            createdAt: Date.now()
        };
        await PromptStorage.save(newPrompt);
        await buildContextMenusFn();
        await markPendingPromptReveal(newId);
        try { chrome.runtime.sendMessage({ type: 'PROMPTS_UPDATED', action: 'create', promptId: newId, prompt: newPrompt }); } catch { /* popup may be closed */ }

        // Show toast
        if (tab?.id) {
            try {
                await chrome.tabs.sendMessage(tab.id, { type: 'SAVE_FROM_CONTEXT_MENU_SUCCESS' });
            } catch (e) {
                try {
                    await chrome.scripting.executeScript({
                        target: { tabId: tab.id },
                        func: (t) => {
                            const n = document.createElement('div');
                            n.textContent = `✅ "${t}" added to Prompt Ark`;
                            n.style.cssText = 'position:fixed;top:20px;right:20px;z-index:999999;padding:12px 20px;background:#10b981;color:white;border-radius:8px;font-size:14px;font-family:system-ui;box-shadow:0 4px 12px rgba(0,0,0,0.3);transition:opacity 0.3s;';
                            document.body.appendChild(n);
                            setTimeout(() => { n.style.opacity = '0'; setTimeout(() => n.remove(), 300); }, 2500);
                        },
                        args: [heuristicTitle]
                    });
                } catch (e2) { /* OK */ }
            }
        }

        if (shouldEnrichPromptMetadata(newPrompt)) {
            await asyncEnrichPromptFn(newId, selectedText);
        }
        return;
    }

    // --- Use Prompt ---
    if (!menuId.startsWith('prompt-ark-') || menuId === 'prompt-ark-parent') return;

    const promptId = menuId.replace('prompt-ark-', '');
    const prompts = await getPromptsFn();
    const prompt = prompts.find(p => p.id === promptId);
    if (!prompt) return;

    const selectedText = (info.selectionText || '').trim();

    const target = prompts.find(p => p.id === promptId);
    if (target) {
        target.usageCount = (target.usageCount || 0) + 1;
        target.lastUsedAt = Date.now();
        await PromptStorage.update(target);
    }

    const deliveryMode = (tab?.url && isAIChatUrl(tab.url))
        ? 'inject_current_tab'
        : 'open_default_ai';

    if (tab?.id) {
        try {
            const response = await chrome.tabs.sendMessage(tab.id, {
                type: 'RUN_CONTEXT_MENU_PROMPT',
                prompt,
                selectedText,
                deliveryMode
            });
            if (response?.success) return;
            console.warn('[ContextMenu] Prompt workflow failed on source page:', response?.error || 'UNKNOWN_ERROR');
        } catch (e) {
            console.warn('[ContextMenu] Prompt workflow delegation failed:', e);
        }
        await notifyContextPromptUnavailable(tab.id);
    }
}
