// lib/ai/enrich.js — Async AI enrichment (title/category/tags)
import { PromptStorage } from '../storage.js';

/**
 * Async AI Enrichment — runs after save, non-blocking
 * @param {string} promptId
 * @param {string} content
 * @param {Function} extractTitleAndCategoryFn - Injected to avoid circular dep
 * @param {Function} getPromptsFn
 * @param {Function} buildContextMenusFn
 */
export async function asyncEnrichPrompt(promptId, content, extractTitleAndCategoryFn, getPromptsFn, buildContextMenusFn) {
    try {
        console.log('[asyncEnrich] Starting for prompt:', promptId);
        const result = await extractTitleAndCategoryFn(content);
        console.log('[asyncEnrich] Result:', JSON.stringify(result));
        if (!result || (!result.title && !result.category && !result.tags?.length)) {
            console.log('[asyncEnrich] No useful metadata, skipping');
            return;
        }

        const prompts = await getPromptsFn();
        const prompt = prompts.find(p => p.id === promptId);
        if (!prompt) return;

        let changed = false;
        // Only overwrite title if it was auto-generated (not user-typed)
        if (prompt.titleAutoGenerated && result.title) {
            prompt.title = result.title;
            prompt.titleAutoGenerated = false; // AI title is now the real title
            changed = true;
        }
        if (!prompt.category && result.category) {
            prompt.category = result.category; changed = true;
        }
        if (result.tags?.length && (!prompt.tags || prompt.tags.length === 0)) {
            prompt.tags = result.tags; changed = true;
        }

        if (changed) {
            await PromptStorage.update(prompt);
            await buildContextMenusFn();
            // Notify popup with the updated prompt data for fast targeted refresh
            try { chrome.runtime.sendMessage({ type: 'PROMPTS_UPDATED', prompt }); } catch { /* popup may be closed */ }
        }
    } catch (e) {
        console.error('[asyncEnrich] Failed:', e);
    }
}
