// lib/ai/enrich.js — Async AI enrichment (title/category/tags)
import { PromptStorage } from '../storage.js';
import { normalizeTags } from '../text-analysis.js';
import { applyClassificationResult, CATEGORY_TYPES, isConfirmedCategoryType, resolveSystemCategoryKey } from '../taxonomy.js';
import { getCustomCategoriesForClassification } from '../prompt-metadata.js';

/**
 * Async AI Enrichment — runs after save, non-blocking
 * @param {string} promptId
 * @param {string} content
 * @param {Function} extractTitleAndCategoryFn - Injected to avoid circular dep
 * @param {Function} getPromptsFn
 * @param {Function} buildContextMenusFn
 */
export async function asyncEnrichPrompt(promptId, content, extractTitleAndCategoryFn, getPromptsFn, buildContextMenusFn, locale = 'zh_CN') {
    try {
        console.log('[asyncEnrich] Starting for prompt:', promptId);
        const prompts = await getPromptsFn();
        const prompt = prompts.find(p => p.id === promptId);
        if (!prompt) return;
        const result = await extractTitleAndCategoryFn(content, {
            customCategories: getCustomCategoriesForClassification(prompts, promptId),
            promptId,
            locale,
        });
        console.log('[asyncEnrich] Result:', JSON.stringify(result));
        if (!result || (!result.title && !result.recommended_category_key && !result.tags?.length && !result.output_modality)) {
            console.log('[asyncEnrich] No useful metadata, skipping');
            return;
        }

        let changed = false;
        // Only overwrite title if it was auto-generated (not user-typed)
        if (prompt.titleAutoGenerated && result.title) {
            prompt.title = result.title;
            prompt.titleAutoGenerated = false; // AI title is now the real title
            changed = true;
        }
        if (
            result.output_modality &&
            !prompt.output_modality_locked &&
            (prompt.needs_output_modality_review || !prompt.output_modality)
        ) {
            prompt.output_modality = result.output_modality;
            if (prompt.needs_output_modality_review) {
                prompt.needs_output_modality_review = false;
                changed = true;
            }
            changed = true;
        }
        if (result.tags?.length && normalizeTags(prompt.tags).length === 0) {
            prompt.tags = normalizeTags(result.tags);
            changed = true;
        }
        if (Number.isFinite(Number(result.confidence))) {
            const nextConfidence = Number(result.confidence);
            if (prompt.classification_confidence !== nextConfidence) {
                prompt.classification_confidence = nextConfidence;
                changed = true;
            }
        }

        const recommendedType = result.recommended_category_type === CATEGORY_TYPES.CUSTOM
            ? CATEGORY_TYPES.CUSTOM
            : CATEGORY_TYPES.SYSTEM;
        const recommendedKey = recommendedType === CATEGORY_TYPES.CUSTOM
            ? String(result.recommended_category_key || '').trim()
            : await resolveSystemCategoryKey(result.recommended_category_key) || String(result.recommended_category_key || '').trim();
        const recommendedConfidence = Number.isFinite(Number(result.confidence)) ? Number(result.confidence) : undefined;

        if (recommendedKey) {
            if (prompt.ai_category_type !== recommendedType) {
                prompt.ai_category_type = recommendedType;
                changed = true;
            }
            if (prompt.ai_category_key !== recommendedKey) {
                prompt.ai_category_key = recommendedKey;
                changed = true;
            }
            if (prompt.ai_category_confidence !== recommendedConfidence) {
                prompt.ai_category_confidence = recommendedConfidence;
                changed = true;
            }
        }

        if (result.recommended_category_key && (prompt.needs_category_review || !isConfirmedCategoryType(prompt.category_type))) {
            const isManualCustomReview = prompt.category_type === CATEGORY_TYPES.CUSTOM && prompt.needs_category_review;

            if (!isManualCustomReview) {
                const classifiedPrompt = await applyClassificationResult(prompt, result, { locale });
                if (
                    classifiedPrompt.category_type !== prompt.category_type ||
                    classifiedPrompt.category_key !== prompt.category_key ||
                    classifiedPrompt.category !== prompt.category
                ) {
                    prompt.category_type = classifiedPrompt.category_type;
                    prompt.category_key = classifiedPrompt.category_key;
                    prompt.category = classifiedPrompt.category;
                    changed = true;
                }
            }

            const nextNeedsReview = isManualCustomReview
                ? true
                : (!Number.isFinite(recommendedConfidence) || recommendedConfidence < 0.8);
            if (prompt.needs_category_review !== nextNeedsReview) {
                prompt.needs_category_review = nextNeedsReview;
                changed = true;
            }
        }

        if (changed) {
            await PromptStorage.update(prompt);
            await buildContextMenusFn();
            // Notify popup with the updated prompt data for fast targeted refresh
            try { chrome.runtime.sendMessage({ type: 'PROMPTS_UPDATED', prompt }); } catch { /* popup may be closed */ }
        }
    } catch (e) {
        console.error('[asyncEnrich] Failed:', e);
    }
}
