import type { Prompt } from './prompt';

export type MessageType =
  | 'GET_PROMPTS'
  | 'SAVE_PROMPT'
  | 'UPDATE_PROMPT'
  | 'DELETE_PROMPT'
  | 'EXPORT_PROMPTS'
  | 'IMPORT_PROMPTS'
  | 'TOGGLE_FAVORITE'
  | 'TRACK_USAGE'
  | 'GET_PROMPT_HISTORY'
  | 'RESTORE_PROMPT_VERSION'
  | 'BATCH_RENAME_CATEGORY'
  | 'GET_PROVIDERS'
  | 'SAVE_PROVIDERS'
  | 'GET_SHORTCUTS'
  | 'GENERATE_TEXT'
  | 'OPTIMIZE_PROMPT'
  | 'TRANSLATE_PROMPT'
  | 'AUTO_EXTRACT'
  | 'COMPOSE_PROMPT'
  | 'CAPTURE_PAGE_CONTEXT'
  | 'GET_PAGE_CONTEXT'
  | 'GET_I18N_DICT'
  | 'LANGUAGE_CHANGED'
  | 'GENERATE_VIDEO_PROMPT'
  | 'GENERATE_YOUTUBE_PROMPT'
  | 'QUICK_ADD_SELECTION'
  | 'SMART_CONVERT_SELECTION'
  | 'GENERATE_SHARE_TEXT'
  | 'SHARE_TO_PLATFORM'
  | 'ARTICLE_SHARE_TO_PLATFORM'
  | 'GET_SYNC_SETTINGS'
  | 'SAVE_SYNC_SETTINGS'
  | 'FORCE_GIST_SYNC'
  | 'FORCE_WEBDAV_SYNC'
  | 'FORCE_OBSIDIAN_SYNC'
  | 'FORCE_OBSIDIAN_LOCAL_SYNC'
  | 'GET_GITHUB_TOKEN'
  | 'GET_SYNC_USAGE'
  | 'GET_DEFAULT_PLATFORM'
  | 'SET_DEFAULT_PLATFORM'
  | 'SHARE_PROMPT'
  | 'CHECK_HUB_LOGIN'
  | 'PUBLISH_TO_HUB'
  | 'PUBLISH_PACK_TO_HUB'
  | 'PROMPT_ARK_AUTH_SYNC'
  | 'GENERATE_SKILL'
  | 'GET_SKILLS'
  | 'PUSH_SKILL'
  | 'DELETE_SKILL'
  | 'GET_OPENCLAW_SETTINGS'
  | 'SAVE_OPENCLAW_SETTINGS'
  | 'GET_IMAGE_PROMPT_SETTINGS'
  | 'SAVE_IMAGE_PROMPT_SETTINGS'
  | 'INSERT_PROMPT'
  | 'INSERT_SHARE_CONTENT'
  | 'SHOW_PROMPT_PICKER'
  | 'SAVE_FROM_CONTEXT_MENU_SUCCESS'
  | 'SMART_CONVERT_STATUS'
  | 'GET_PLATFORM'
  | 'GRAB_CONTEXT'
  | 'UPDATE_I18N_DICT'
  | 'GET_SELECTION'
  | 'GET_PAGE_TEXT'
  | 'COPY_TO_CLIPBOARD'
  | 'SHOW_ARTICLE_SHARE_PICKER'
  | 'ARTICLE_SHARE_PICK_PLATFORM'
  | 'IMAGE_PROMPT_SETTINGS_CHANGED'
  | 'PROMPTS_UPDATED';

export interface BaseMessage {
  type: MessageType;
}

export interface GetPromptsMessage extends BaseMessage {
  type: 'GET_PROMPTS';
}

export interface GetPromptsResponse {
  success: boolean;
  prompts: Prompt[];
}

export interface SavePromptMessage extends BaseMessage {
  type: 'SAVE_PROMPT';
  prompt: Omit<Prompt, 'id' | 'createdAt'>;
}