export interface Prompt {
  id: string;
  title: string;
  content: string;
  category: string;
  tags: string[];
  shortcut?: string;
  variables: string[];
  versions: PromptVersion[];
  usageCount: number;
  lastUsedAt: number | null;
  favorite: boolean;
  createdAt: number;
  updatedAt?: number;
  builtIn?: boolean;
  titleAutoGenerated?: boolean;
  sourceContext?: SourceContext;
  videoData?: VideoData;
}

export interface PromptVersion {
  versionId: string;
  content: string;
  timestamp: number;
}

export interface SourceContext {
  text: string;
  pageTitle?: string;
  pageUrl?: string;
  capturedAt: number;
  convertMethod: 'quick_add' | 'smart_convert';
}

export interface VideoData {
  url: string;
  transcript?: string;
  summary?: string;
}