import type { MetadataExtractionResult } from '@/types/ai';

export interface EnrichOptions {
  promptId: string;
  content: string;
  titleAutoGenerated: boolean;
}

export interface EnrichCallbacks {
  extractMetadata: (content: string, lang: string) => Promise<MetadataExtractionResult | null>;
  getPrompts: () => Promise<Array<{ id: string; title: string; category?: string; tags?: string[]; titleAutoGenerated?: boolean }>>;
  updatePrompt: (prompt: unknown) => Promise<void>;
  buildContextMenus: () => Promise<void>;
}

export interface EnrichResult {
  success: boolean;
  updated: boolean;
  changes: {
    title?: boolean;
    category?: boolean;
    tags?: boolean;
  };
}

export async function enrichPrompt(
  options: EnrichOptions,
  callbacks: EnrichCallbacks,
  lang = 'zh'
): Promise<EnrichResult> {
  const { promptId, content, titleAutoGenerated } = options;
  const { extractMetadata, getPrompts, updatePrompt, buildContextMenus } = callbacks;

  try {
    const result = await extractMetadata(content, lang);

    if (!result || (!result.title && !result.category && !result.tags?.length)) {
      return {
        success: true,
        updated: false,
        changes: {},
      };
    }

    const prompts = await getPrompts();
    const prompt = prompts.find(p => p.id === promptId);

    if (!prompt) {
      return {
        success: false,
        updated: false,
        changes: {},
      };
    }

    const changes: EnrichResult['changes'] = {};
    const updates: typeof prompt = { ...prompt };

    if (titleAutoGenerated && result.title) {
      updates.title = result.title;
      updates.titleAutoGenerated = false;
      changes.title = true;
    }

    if (!prompt.category && result.category) {
      updates.category = result.category;
      changes.category = true;
    }

    if (result.tags?.length && (!prompt.tags || prompt.tags.length === 0)) {
      updates.tags = result.tags;
      changes.tags = true;
    }

    const hasChanges = Object.keys(changes).length > 0;

    if (hasChanges) {
      await updatePrompt(updates);
      await buildContextMenus();

      try {
        chrome.runtime.sendMessage({ type: 'PROMPTS_UPDATED', prompt: updates });
      } catch {
        // Popup may be closed, ignore
      }
    }

    return {
      success: true,
      updated: hasChanges,
      changes,
    };
  } catch (error) {
    return {
      success: false,
      updated: false,
      changes: {},
    };
  }
}

export async function asyncEnrichPrompt(
  promptId: string,
  content: string,
  callbacks: EnrichCallbacks,
  lang = 'zh'
): Promise<void> {
  try {
    const prompts = await callbacks.getPrompts();
    const prompt = prompts.find(p => p.id === promptId);

    if (!prompt) return;

    await enrichPrompt(
      {
        promptId,
        content,
        titleAutoGenerated: prompt.titleAutoGenerated ?? false,
      },
      callbacks,
      lang
    );
  } catch {
    // Silent fail for async enrichment
  }
}
